---
- name: create airflow dir
  file:
    path: /home/de-devtools/airflow
    state: directory

# src: https://github.com/puckel/docker-airflow
- name: steal airflow.cfg file from puckel
  command: 'curl https://raw.githubusercontent.com/puckel/docker-airflow/master/config/airflow.cfg >> /home/de-devtools/airflow/airflow.cfg'

- name: set airflow env vars
  command: 'export AIRFLOW_HOME=/home/de-devtools/airflow'
