- name: initialize airflow db
  become: airflow
  command: "airflow initdb"

- name: set airflow metadata db to local postgres
  lineinfile:
    path: ~/airflow/airflow.cfg
    regexp: '^sql_alchemy_conn = sqlite:.*$'
    line: 'sql_alchemy_conn = postgres://postgres@localhost:5432'
    state: present

- name: reset db again with postgres conn
  become: airflow
  command: "airflow resetdb --yes"
