---
- name: create airflow group
  group:
    name: airflow

- name: create airflow user
  user:
    name: airflow
    group: airflow
    shell: /bin/bash

- name: create airflow run dir
  file:
    path: "/run/airflow"
    owner: airflow
    group: airflow
    state: directory

- name: create airflow home
  file:
    path: "/home/de-devtools/airflow"
    owner: airflow
    group: airflow
    state: directory

- name: set airflow home dir as environment variable
  lineinfile:
    path: /etc/environment
    line: 'AIRFLOW_HOME=/home/de-devtools/airflow'

- name: install pip dependencies
  pip:
    executable: pip3
    name: ['psycopg2-binary']

- name: install airflow
  pip:
    executable: pip3
    name: ['apache-airflow']
