---
- name: create airflow group
  group:
    name: airflow

- name: create airflow user
  user:
    name: airflow
    group: airflow
    shell: /bin/bash

- name: create airflow run dir
  file:
    path: "/run/airflow"
    owner: airflow
    group: airflow
    state: directory

- name: create airflow home
  file:
    path: "/home/de-devtools/airflow"
    owner: airflow
    group: airflow
    state: directory

- name: set airflow home dir as environment variable
  lineinfile:
    path: /etc/environment
    line: 'AIRFLOW_HOME=/home/de-devtools/airflow'

- name: install airflow
  pip:
    executable: pip3
    name: apache-airflow

- name: initialize airflow db
  become: airflow  
  command: "airflow initdb"

- name: set airflow metadata db to local postgres
  lineinfile:
    path: ~/airflow/airflow.cfg
    regexp: '^sql_alchemy_conn = sqlite:////root/airflow/airflow.db.*$'
    line: 'sql_alchemy_conn = postgres://postgres@localhost:5432'
    state: present

- name: remove sqlite db
  become: airflow
  command: "rm ~/airflow/airflow.db"

- name: init db again with postgres conn
  become: airflow
  command: "airflow initdb"
