---
- name: create airflow dir
  file:
    path: /home/de-devtools/airflow
    state: directory

# src: https://github.com/puckel/docker-airflow
- name: steal airflow.cfg file from puckel
  get_url:
    url: https://raw.githubusercontent.com/puckel/docker-airflow/master/config/airflow.cfg
    dest: /home/de-devtools/airflow/airflow.cfg

- name: set airflow env vars
  command: 'AIRFLOW_HOME=/home/de-devtools/airflow'

- name: set airflow metadata db to local postgres
  lineinfile:
    path: /home/de-devtools/airflow/airflow.cfg
    regexp: '^# sql_alchemy_conn = sqlite:////tmp/airflow.db$'
    line: 'sql_alchemy_conn = postgres://postgres@localhost:5432'
    state: present

# - name: initialize airflow metadata db
#   comannd: 'airflow initdb'
