---
- name: start postgres
  include: start-psqldb.yaml

- name: create airflow user and db in postgres server
  include: postgres-airflow-config.yaml

- name: postgres config to trust airflow user
  include: postgres-trust-airflow.yaml
