---
- name: postgres db config to trust airflow
  include: postgres-trust-airflow.yaml

- name: start postgres as service
  include: postgres-start-service.yaml

- name: create airflow db objects
  include: postgres-airflow-config.yaml

- name: install apache airflow
  include: airflow-install.yaml
